// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddReactionArgs {
    pub message_id: u64,
    pub emoji: String,
}

impl From<AddReactionArgs> for super::Reducer {
    fn from(args: AddReactionArgs) -> Self {
        Self::AddReaction {
            message_id: args.message_id,
            emoji: args.emoji,
        }
    }
}

impl __sdk::InModule for AddReactionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_reaction`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_reaction {
    /// Request that the remote module invoke the reducer `add_reaction` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_reaction:add_reaction_then`] to run a callback after the reducer completes.
    fn add_reaction(&self, message_id: u64, emoji: String) -> __sdk::Result<()> {
        self.add_reaction_then(message_id, emoji, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_reaction` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_reaction_then(
        &self,
        message_id: u64,
        emoji: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_reaction for super::RemoteReducers {
    fn add_reaction_then(
        &self,
        message_id: u64,
        emoji: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AddReactionArgs { message_id, emoji }, callback)
    }
}
