// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChannelReadState {
    pub id: u64,
    pub identity: __sdk::Identity,
    pub channel_id: u64,
    pub last_read_msg_id: u64,
}

impl __sdk::InModule for ChannelReadState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChannelReadState`.
///
/// Provides typed access to columns for query building.
pub struct ChannelReadStateCols {
    pub id: __sdk::__query_builder::Col<ChannelReadState, u64>,
    pub identity: __sdk::__query_builder::Col<ChannelReadState, __sdk::Identity>,
    pub channel_id: __sdk::__query_builder::Col<ChannelReadState, u64>,
    pub last_read_msg_id: __sdk::__query_builder::Col<ChannelReadState, u64>,
}

impl __sdk::__query_builder::HasCols for ChannelReadState {
    type Cols = ChannelReadStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChannelReadStateCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            channel_id: __sdk::__query_builder::Col::new(table_name, "channel_id"),
            last_read_msg_id: __sdk::__query_builder::Col::new(table_name, "last_read_msg_id"),
        }
    }
}

/// Indexed column accessor struct for the table `ChannelReadState`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChannelReadStateIxCols {
    pub id: __sdk::__query_builder::IxCol<ChannelReadState, u64>,
    pub identity: __sdk::__query_builder::IxCol<ChannelReadState, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ChannelReadState {
    type IxCols = ChannelReadStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChannelReadStateIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChannelReadState {}
