// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::channel_read_state_type::ChannelReadState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `channel_read_state`.
///
/// Obtain a handle from the [`ChannelReadStateTableAccess::channel_read_state`] method on [`super::RemoteTables`],
/// like `ctx.db.channel_read_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.channel_read_state().on_insert(...)`.
pub struct ChannelReadStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChannelReadState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `channel_read_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChannelReadStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChannelReadStateTableHandle`], which mediates access to the table `channel_read_state`.
    fn channel_read_state(&self) -> ChannelReadStateTableHandle<'_>;
}

impl ChannelReadStateTableAccess for super::RemoteTables {
    fn channel_read_state(&self) -> ChannelReadStateTableHandle<'_> {
        ChannelReadStateTableHandle {
            imp: self.imp.get_table::<ChannelReadState>("channel_read_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChannelReadStateInsertCallbackId(__sdk::CallbackId);
pub struct ChannelReadStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ChannelReadStateTableHandle<'ctx> {
    type Row = ChannelReadState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChannelReadState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChannelReadStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChannelReadStateInsertCallbackId {
        ChannelReadStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChannelReadStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChannelReadStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChannelReadStateDeleteCallbackId {
        ChannelReadStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChannelReadStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChannelReadStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChannelReadStateTableHandle<'ctx> {
    type UpdateCallbackId = ChannelReadStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChannelReadStateUpdateCallbackId {
        ChannelReadStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChannelReadStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `channel_read_state`,
/// which allows point queries on the field of the same name
/// via the [`ChannelReadStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.channel_read_state().id().find(...)`.
pub struct ChannelReadStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChannelReadState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChannelReadStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `channel_read_state`.
    pub fn id(&self) -> ChannelReadStateIdUnique<'ctx> {
        ChannelReadStateIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChannelReadStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ChannelReadState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChannelReadState>("channel_read_state");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChannelReadState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChannelReadState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChannelReadState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait channel_read_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChannelReadState`.
    fn channel_read_state(&self) -> __sdk::__query_builder::Table<ChannelReadState>;
}

impl channel_read_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn channel_read_state(&self) -> __sdk::__query_builder::Table<ChannelReadState> {
        __sdk::__query_builder::Table::new("channel_read_state")
    }
}
