// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateServerArgs {
    pub name: String,
    pub description: Option<String>,
}

impl From<CreateServerArgs> for super::Reducer {
    fn from(args: CreateServerArgs) -> Self {
        Self::CreateServer {
            name: args.name,
            description: args.description,
        }
    }
}

impl __sdk::InModule for CreateServerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_server`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_server {
    /// Request that the remote module invoke the reducer `create_server` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_server:create_server_then`] to run a callback after the reducer completes.
    fn create_server(&self, name: String, description: Option<String>) -> __sdk::Result<()> {
        self.create_server_then(name, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_server` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_server_then(
        &self,
        name: String,
        description: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_server for super::RemoteReducers {
    fn create_server_then(
        &self,
        name: String,
        description: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateServerArgs { name, description }, callback)
    }
}
