// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::channel_type_type::ChannelType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateChannelArgs {
    pub server_id: u64,
    pub name: String,
    pub channel_type: ChannelType,
}

impl From<CreateChannelArgs> for super::Reducer {
    fn from(args: CreateChannelArgs) -> Self {
        Self::CreateChannel {
            server_id: args.server_id,
            name: args.name,
            channel_type: args.channel_type,
        }
    }
}

impl __sdk::InModule for CreateChannelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_channel {
    /// Request that the remote module invoke the reducer `create_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_channel:create_channel_then`] to run a callback after the reducer completes.
    fn create_channel(
        &self,
        server_id: u64,
        name: String,
        channel_type: ChannelType,
    ) -> __sdk::Result<()> {
        self.create_channel_then(server_id, name, channel_type, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_channel` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_channel_then(
        &self,
        server_id: u64,
        name: String,
        channel_type: ChannelType,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_channel for super::RemoteReducers {
    fn create_channel_then(
        &self,
        server_id: u64,
        name: String,
        channel_type: ChannelType,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateChannelArgs {
                server_id,
                name,
                channel_type,
            },
            callback,
        )
    }
}
