// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateThreadArgs {
    pub channel_id: u64,
    pub name: String,
    pub initial_message: String,
}

impl From<CreateThreadArgs> for super::Reducer {
    fn from(args: CreateThreadArgs) -> Self {
        Self::CreateThread {
            channel_id: args.channel_id,
            name: args.name,
            initial_message: args.initial_message,
        }
    }
}

impl __sdk::InModule for CreateThreadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_thread`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_thread {
    /// Request that the remote module invoke the reducer `create_thread` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_thread:create_thread_then`] to run a callback after the reducer completes.
    fn create_thread(
        &self,
        channel_id: u64,
        name: String,
        initial_message: String,
    ) -> __sdk::Result<()> {
        self.create_thread_then(channel_id, name, initial_message, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_thread` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_thread_then(
        &self,
        channel_id: u64,
        name: String,
        initial_message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_thread for super::RemoteReducers {
    fn create_thread_then(
        &self,
        channel_id: u64,
        name: String,
        initial_message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateThreadArgs {
                channel_id,
                name,
                initial_message,
            },
            callback,
        )
    }
}
