// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct JoinServerArgs {
    pub server_id: u64,
}

impl From<JoinServerArgs> for super::Reducer {
    fn from(args: JoinServerArgs) -> Self {
        Self::JoinServer {
            server_id: args.server_id,
        }
    }
}

impl __sdk::InModule for JoinServerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `join_server`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait join_server {
    /// Request that the remote module invoke the reducer `join_server` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`join_server:join_server_then`] to run a callback after the reducer completes.
    fn join_server(&self, server_id: u64) -> __sdk::Result<()> {
        self.join_server_then(server_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `join_server` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn join_server_then(
        &self,
        server_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl join_server for super::RemoteReducers {
    fn join_server_then(
        &self,
        server_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(JoinServerArgs { server_id }, callback)
    }
}
