// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Reaction {
    pub id: u64,
    pub message_id: u64,
    pub identity: __sdk::Identity,
    pub emoji: String,
}

impl __sdk::InModule for Reaction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Reaction`.
///
/// Provides typed access to columns for query building.
pub struct ReactionCols {
    pub id: __sdk::__query_builder::Col<Reaction, u64>,
    pub message_id: __sdk::__query_builder::Col<Reaction, u64>,
    pub identity: __sdk::__query_builder::Col<Reaction, __sdk::Identity>,
    pub emoji: __sdk::__query_builder::Col<Reaction, String>,
}

impl __sdk::__query_builder::HasCols for Reaction {
    type Cols = ReactionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ReactionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            message_id: __sdk::__query_builder::Col::new(table_name, "message_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            emoji: __sdk::__query_builder::Col::new(table_name, "emoji"),
        }
    }
}

/// Indexed column accessor struct for the table `Reaction`.
///
/// Provides typed access to indexed columns for query building.
pub struct ReactionIxCols {
    pub id: __sdk::__query_builder::IxCol<Reaction, u64>,
    pub message_id: __sdk::__query_builder::IxCol<Reaction, u64>,
}

impl __sdk::__query_builder::HasIxCols for Reaction {
    type IxCols = ReactionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ReactionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            message_id: __sdk::__query_builder::IxCol::new(table_name, "message_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Reaction {}
