// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::reaction_type::Reaction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `reaction`.
///
/// Obtain a handle from the [`ReactionTableAccess::reaction`] method on [`super::RemoteTables`],
/// like `ctx.db.reaction()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.reaction().on_insert(...)`.
pub struct ReactionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Reaction>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `reaction`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ReactionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ReactionTableHandle`], which mediates access to the table `reaction`.
    fn reaction(&self) -> ReactionTableHandle<'_>;
}

impl ReactionTableAccess for super::RemoteTables {
    fn reaction(&self) -> ReactionTableHandle<'_> {
        ReactionTableHandle {
            imp: self.imp.get_table::<Reaction>("reaction"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ReactionInsertCallbackId(__sdk::CallbackId);
pub struct ReactionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ReactionTableHandle<'ctx> {
    type Row = Reaction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Reaction> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ReactionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReactionInsertCallbackId {
        ReactionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ReactionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ReactionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReactionDeleteCallbackId {
        ReactionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ReactionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ReactionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ReactionTableHandle<'ctx> {
    type UpdateCallbackId = ReactionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ReactionUpdateCallbackId {
        ReactionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ReactionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `reaction`,
/// which allows point queries on the field of the same name
/// via the [`ReactionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.reaction().id().find(...)`.
pub struct ReactionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Reaction, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ReactionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `reaction`.
    pub fn id(&self) -> ReactionIdUnique<'ctx> {
        ReactionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ReactionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Reaction> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Reaction>("reaction");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Reaction>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Reaction>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Reaction`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait reactionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Reaction`.
    fn reaction(&self) -> __sdk::__query_builder::Table<Reaction>;
}

impl reactionQueryTableAccess for __sdk::QueryTableAccessor {
    fn reaction(&self) -> __sdk::__query_builder::Table<Reaction> {
        __sdk::__query_builder::Table::new("reaction")
    }
}
