// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendMessageArgs {
    pub channel_id: u64,
    pub content: String,
    pub thread_id: Option<u64>,
    pub reply_to_id: Option<u64>,
}

impl From<SendMessageArgs> for super::Reducer {
    fn from(args: SendMessageArgs) -> Self {
        Self::SendMessage {
            channel_id: args.channel_id,
            content: args.content,
            thread_id: args.thread_id,
            reply_to_id: args.reply_to_id,
        }
    }
}

impl __sdk::InModule for SendMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_message {
    /// Request that the remote module invoke the reducer `send_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`send_message:send_message_then`] to run a callback after the reducer completes.
    fn send_message(
        &self,
        channel_id: u64,
        content: String,
        thread_id: Option<u64>,
        reply_to_id: Option<u64>,
    ) -> __sdk::Result<()> {
        self.send_message_then(channel_id, content, thread_id, reply_to_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `send_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn send_message_then(
        &self,
        channel_id: u64,
        content: String,
        thread_id: Option<u64>,
        reply_to_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl send_message for super::RemoteReducers {
    fn send_message_then(
        &self,
        channel_id: u64,
        content: String,
        thread_id: Option<u64>,
        reply_to_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SendMessageArgs {
                channel_id,
                content,
                thread_id,
                reply_to_id,
            },
            callback,
        )
    }
}
