// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::member_role_type::MemberRole;
use super::server_member_type::ServerMember;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `server_member`.
///
/// Obtain a handle from the [`ServerMemberTableAccess::server_member`] method on [`super::RemoteTables`],
/// like `ctx.db.server_member()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_member().on_insert(...)`.
pub struct ServerMemberTableHandle<'ctx> {
    imp: __sdk::TableHandle<ServerMember>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `server_member`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ServerMemberTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ServerMemberTableHandle`], which mediates access to the table `server_member`.
    fn server_member(&self) -> ServerMemberTableHandle<'_>;
}

impl ServerMemberTableAccess for super::RemoteTables {
    fn server_member(&self) -> ServerMemberTableHandle<'_> {
        ServerMemberTableHandle {
            imp: self.imp.get_table::<ServerMember>("server_member"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ServerMemberInsertCallbackId(__sdk::CallbackId);
pub struct ServerMemberDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ServerMemberTableHandle<'ctx> {
    type Row = ServerMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServerMember> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ServerMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerMemberInsertCallbackId {
        ServerMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ServerMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerMemberDeleteCallbackId {
        ServerMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ServerMemberUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ServerMemberTableHandle<'ctx> {
    type UpdateCallbackId = ServerMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ServerMemberUpdateCallbackId {
        ServerMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ServerMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `server_member`,
/// which allows point queries on the field of the same name
/// via the [`ServerMemberIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_member().id().find(...)`.
pub struct ServerMemberIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ServerMember, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ServerMemberTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `server_member`.
    pub fn id(&self) -> ServerMemberIdUnique<'ctx> {
        ServerMemberIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ServerMemberIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ServerMember> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ServerMember>("server_member");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ServerMember>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ServerMember>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ServerMember`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait server_memberQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ServerMember`.
    fn server_member(&self) -> __sdk::__query_builder::Table<ServerMember>;
}

impl server_memberQueryTableAccess for __sdk::QueryTableAccessor {
    fn server_member(&self) -> __sdk::__query_builder::Table<ServerMember> {
        __sdk::__query_builder::Table::new("server_member")
    }
}
