// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::member_role_type::MemberRole;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ServerMember {
    pub id: u64,
    pub server_id: u64,
    pub identity: __sdk::Identity,
    pub role: MemberRole,
    pub joined_at: __sdk::Timestamp,
}

impl __sdk::InModule for ServerMember {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ServerMember`.
///
/// Provides typed access to columns for query building.
pub struct ServerMemberCols {
    pub id: __sdk::__query_builder::Col<ServerMember, u64>,
    pub server_id: __sdk::__query_builder::Col<ServerMember, u64>,
    pub identity: __sdk::__query_builder::Col<ServerMember, __sdk::Identity>,
    pub role: __sdk::__query_builder::Col<ServerMember, MemberRole>,
    pub joined_at: __sdk::__query_builder::Col<ServerMember, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ServerMember {
    type Cols = ServerMemberCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ServerMemberCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            server_id: __sdk::__query_builder::Col::new(table_name, "server_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            joined_at: __sdk::__query_builder::Col::new(table_name, "joined_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ServerMember`.
///
/// Provides typed access to indexed columns for query building.
pub struct ServerMemberIxCols {
    pub id: __sdk::__query_builder::IxCol<ServerMember, u64>,
    pub server_id: __sdk::__query_builder::IxCol<ServerMember, u64>,
}

impl __sdk::__query_builder::HasIxCols for ServerMember {
    type IxCols = ServerMemberIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ServerMemberIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            server_id: __sdk::__query_builder::IxCol::new(table_name, "server_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ServerMember {}
