// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SystemNotification {
    pub id: u64,
    pub target: __sdk::Identity,
    pub title: String,
    pub body: String,
}

impl __sdk::InModule for SystemNotification {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SystemNotification`.
///
/// Provides typed access to columns for query building.
pub struct SystemNotificationCols {
    pub id: __sdk::__query_builder::Col<SystemNotification, u64>,
    pub target: __sdk::__query_builder::Col<SystemNotification, __sdk::Identity>,
    pub title: __sdk::__query_builder::Col<SystemNotification, String>,
    pub body: __sdk::__query_builder::Col<SystemNotification, String>,
}

impl __sdk::__query_builder::HasCols for SystemNotification {
    type Cols = SystemNotificationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SystemNotificationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            target: __sdk::__query_builder::Col::new(table_name, "target"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
        }
    }
}

/// Indexed column accessor struct for the table `SystemNotification`.
///
/// Provides typed access to indexed columns for query building.
pub struct SystemNotificationIxCols {
    pub id: __sdk::__query_builder::IxCol<SystemNotification, u64>,
}

impl __sdk::__query_builder::HasIxCols for SystemNotification {
    type IxCols = SystemNotificationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SystemNotificationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SystemNotification {}
