// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::system_notification_type::SystemNotification;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `system_notification`.
///
/// Obtain a handle from the [`SystemNotificationTableAccess::system_notification`] method on [`super::RemoteTables`],
/// like `ctx.db.system_notification()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_notification().on_insert(...)`.
pub struct SystemNotificationTableHandle<'ctx> {
    imp: __sdk::TableHandle<SystemNotification>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `system_notification`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SystemNotificationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SystemNotificationTableHandle`], which mediates access to the table `system_notification`.
    fn system_notification(&self) -> SystemNotificationTableHandle<'_>;
}

impl SystemNotificationTableAccess for super::RemoteTables {
    fn system_notification(&self) -> SystemNotificationTableHandle<'_> {
        SystemNotificationTableHandle {
            imp: self
                .imp
                .get_table::<SystemNotification>("system_notification"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SystemNotificationInsertCallbackId(__sdk::CallbackId);
pub struct SystemNotificationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SystemNotificationTableHandle<'ctx> {
    type Row = SystemNotification;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SystemNotification> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SystemNotificationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemNotificationInsertCallbackId {
        SystemNotificationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SystemNotificationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SystemNotificationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemNotificationDeleteCallbackId {
        SystemNotificationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SystemNotificationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SystemNotificationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SystemNotificationTableHandle<'ctx> {
    type UpdateCallbackId = SystemNotificationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SystemNotificationUpdateCallbackId {
        SystemNotificationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SystemNotificationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `system_notification`,
/// which allows point queries on the field of the same name
/// via the [`SystemNotificationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_notification().id().find(...)`.
pub struct SystemNotificationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SystemNotification, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SystemNotificationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `system_notification`.
    pub fn id(&self) -> SystemNotificationIdUnique<'ctx> {
        SystemNotificationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SystemNotificationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SystemNotification> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SystemNotification>("system_notification");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SystemNotification>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SystemNotification>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SystemNotification`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait system_notificationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SystemNotification`.
    fn system_notification(&self) -> __sdk::__query_builder::Table<SystemNotification>;
}

impl system_notificationQueryTableAccess for __sdk::QueryTableAccessor {
    fn system_notification(&self) -> __sdk::__query_builder::Table<SystemNotification> {
        __sdk::__query_builder::Table::new("system_notification")
    }
}
