// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Thread {
    pub id: u64,
    pub channel_id: u64,
    pub name: String,
    pub creator: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
    pub archived: bool,
    pub last_message_at: __sdk::Timestamp,
}

impl __sdk::InModule for Thread {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Thread`.
///
/// Provides typed access to columns for query building.
pub struct ThreadCols {
    pub id: __sdk::__query_builder::Col<Thread, u64>,
    pub channel_id: __sdk::__query_builder::Col<Thread, u64>,
    pub name: __sdk::__query_builder::Col<Thread, String>,
    pub creator: __sdk::__query_builder::Col<Thread, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<Thread, __sdk::Timestamp>,
    pub archived: __sdk::__query_builder::Col<Thread, bool>,
    pub last_message_at: __sdk::__query_builder::Col<Thread, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Thread {
    type Cols = ThreadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ThreadCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            channel_id: __sdk::__query_builder::Col::new(table_name, "channel_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            creator: __sdk::__query_builder::Col::new(table_name, "creator"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            archived: __sdk::__query_builder::Col::new(table_name, "archived"),
            last_message_at: __sdk::__query_builder::Col::new(table_name, "last_message_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Thread`.
///
/// Provides typed access to indexed columns for query building.
pub struct ThreadIxCols {
    pub channel_id: __sdk::__query_builder::IxCol<Thread, u64>,
    pub id: __sdk::__query_builder::IxCol<Thread, u64>,
}

impl __sdk::__query_builder::HasIxCols for Thread {
    type IxCols = ThreadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ThreadIxCols {
            channel_id: __sdk::__query_builder::IxCol::new(table_name, "channel_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Thread {}
