// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::thread_type::Thread;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `thread`.
///
/// Obtain a handle from the [`ThreadTableAccess::thread`] method on [`super::RemoteTables`],
/// like `ctx.db.thread()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.thread().on_insert(...)`.
pub struct ThreadTableHandle<'ctx> {
    imp: __sdk::TableHandle<Thread>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `thread`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ThreadTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ThreadTableHandle`], which mediates access to the table `thread`.
    fn thread(&self) -> ThreadTableHandle<'_>;
}

impl ThreadTableAccess for super::RemoteTables {
    fn thread(&self) -> ThreadTableHandle<'_> {
        ThreadTableHandle {
            imp: self.imp.get_table::<Thread>("thread"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ThreadInsertCallbackId(__sdk::CallbackId);
pub struct ThreadDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ThreadTableHandle<'ctx> {
    type Row = Thread;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Thread> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ThreadInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ThreadInsertCallbackId {
        ThreadInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ThreadInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ThreadDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ThreadDeleteCallbackId {
        ThreadDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ThreadDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ThreadUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ThreadTableHandle<'ctx> {
    type UpdateCallbackId = ThreadUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ThreadUpdateCallbackId {
        ThreadUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ThreadUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `thread`,
/// which allows point queries on the field of the same name
/// via the [`ThreadIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.thread().id().find(...)`.
pub struct ThreadIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Thread, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ThreadTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `thread`.
    pub fn id(&self) -> ThreadIdUnique<'ctx> {
        ThreadIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ThreadIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Thread> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Thread>("thread");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Thread>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Thread>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Thread`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait threadQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Thread`.
    fn thread(&self) -> __sdk::__query_builder::Table<Thread>;
}

impl threadQueryTableAccess for __sdk::QueryTableAccessor {
    fn thread(&self) -> __sdk::__query_builder::Table<Thread> {
        __sdk::__query_builder::Table::new("thread")
    }
}
