// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::typing_indicator_type::TypingIndicator;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `typing_indicator`.
///
/// Obtain a handle from the [`TypingIndicatorTableAccess::typing_indicator`] method on [`super::RemoteTables`],
/// like `ctx.db.typing_indicator()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.typing_indicator().on_insert(...)`.
pub struct TypingIndicatorTableHandle<'ctx> {
    imp: __sdk::TableHandle<TypingIndicator>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `typing_indicator`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TypingIndicatorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TypingIndicatorTableHandle`], which mediates access to the table `typing_indicator`.
    fn typing_indicator(&self) -> TypingIndicatorTableHandle<'_>;
}

impl TypingIndicatorTableAccess for super::RemoteTables {
    fn typing_indicator(&self) -> TypingIndicatorTableHandle<'_> {
        TypingIndicatorTableHandle {
            imp: self.imp.get_table::<TypingIndicator>("typing_indicator"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TypingIndicatorInsertCallbackId(__sdk::CallbackId);
pub struct TypingIndicatorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TypingIndicatorTableHandle<'ctx> {
    type Row = TypingIndicator;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TypingIndicator> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TypingIndicatorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TypingIndicatorInsertCallbackId {
        TypingIndicatorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TypingIndicatorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TypingIndicatorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TypingIndicatorDeleteCallbackId {
        TypingIndicatorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TypingIndicatorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TypingIndicatorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TypingIndicatorTableHandle<'ctx> {
    type UpdateCallbackId = TypingIndicatorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TypingIndicatorUpdateCallbackId {
        TypingIndicatorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TypingIndicatorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `typing_indicator`,
/// which allows point queries on the field of the same name
/// via the [`TypingIndicatorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.typing_indicator().id().find(...)`.
pub struct TypingIndicatorIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TypingIndicator, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TypingIndicatorTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `typing_indicator`.
    pub fn id(&self) -> TypingIndicatorIdUnique<'ctx> {
        TypingIndicatorIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TypingIndicatorIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TypingIndicator> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TypingIndicator>("typing_indicator");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TypingIndicator>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TypingIndicator>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TypingIndicator`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait typing_indicatorQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TypingIndicator`.
    fn typing_indicator(&self) -> __sdk::__query_builder::Table<TypingIndicator>;
}

impl typing_indicatorQueryTableAccess for __sdk::QueryTableAccessor {
    fn typing_indicator(&self) -> __sdk::__query_builder::Table<TypingIndicator> {
        __sdk::__query_builder::Table::new("typing_indicator")
    }
}
