// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::member_role_type::MemberRole;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateMemberRoleArgs {
    pub server_id: u64,
    pub target_identity: __sdk::Identity,
    pub new_role: MemberRole,
}

impl From<UpdateMemberRoleArgs> for super::Reducer {
    fn from(args: UpdateMemberRoleArgs) -> Self {
        Self::UpdateMemberRole {
            server_id: args.server_id,
            target_identity: args.target_identity,
            new_role: args.new_role,
        }
    }
}

impl __sdk::InModule for UpdateMemberRoleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_member_role`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_member_role {
    /// Request that the remote module invoke the reducer `update_member_role` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_member_role:update_member_role_then`] to run a callback after the reducer completes.
    fn update_member_role(
        &self,
        server_id: u64,
        target_identity: __sdk::Identity,
        new_role: MemberRole,
    ) -> __sdk::Result<()> {
        self.update_member_role_then(server_id, target_identity, new_role, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_member_role` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_member_role_then(
        &self,
        server_id: u64,
        target_identity: __sdk::Identity,
        new_role: MemberRole,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_member_role for super::RemoteReducers {
    fn update_member_role_then(
        &self,
        server_id: u64,
        target_identity: __sdk::Identity,
        new_role: MemberRole,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateMemberRoleArgs {
                server_id,
                target_identity,
                new_role,
            },
            callback,
        )
    }
}
