// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserPresence {
    pub identity: __sdk::Identity,
    pub online: bool,
    pub status_text: Option<String>,
    pub last_seen: __sdk::Timestamp,
}

impl __sdk::InModule for UserPresence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserPresence`.
///
/// Provides typed access to columns for query building.
pub struct UserPresenceCols {
    pub identity: __sdk::__query_builder::Col<UserPresence, __sdk::Identity>,
    pub online: __sdk::__query_builder::Col<UserPresence, bool>,
    pub status_text: __sdk::__query_builder::Col<UserPresence, Option<String>>,
    pub last_seen: __sdk::__query_builder::Col<UserPresence, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for UserPresence {
    type Cols = UserPresenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserPresenceCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            online: __sdk::__query_builder::Col::new(table_name, "online"),
            status_text: __sdk::__query_builder::Col::new(table_name, "status_text"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `UserPresence`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserPresenceIxCols {
    pub identity: __sdk::__query_builder::IxCol<UserPresence, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for UserPresence {
    type IxCols = UserPresenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserPresenceIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserPresence {}
