// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::channel_type::Channel;
use super::channel_type_type::ChannelType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `channel`.
///
/// Obtain a handle from the [`ChannelTableAccess::channel`] method on [`super::RemoteTables`],
/// like `ctx.db.channel()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.channel().on_insert(...)`.
pub struct ChannelTableHandle<'ctx> {
    imp: __sdk::TableHandle<Channel>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `channel`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChannelTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChannelTableHandle`], which mediates access to the table `channel`.
    fn channel(&self) -> ChannelTableHandle<'_>;
}

impl ChannelTableAccess for super::RemoteTables {
    fn channel(&self) -> ChannelTableHandle<'_> {
        ChannelTableHandle {
            imp: self.imp.get_table::<Channel>("channel"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChannelInsertCallbackId(__sdk::CallbackId);
pub struct ChannelDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ChannelTableHandle<'ctx> {
    type Row = Channel;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Channel> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChannelInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChannelInsertCallbackId {
        ChannelInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChannelInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChannelDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChannelDeleteCallbackId {
        ChannelDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChannelDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChannelUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChannelTableHandle<'ctx> {
    type UpdateCallbackId = ChannelUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChannelUpdateCallbackId {
        ChannelUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChannelUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `channel`,
/// which allows point queries on the field of the same name
/// via the [`ChannelIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.channel().id().find(...)`.
pub struct ChannelIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Channel, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChannelTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `channel`.
    pub fn id(&self) -> ChannelIdUnique<'ctx> {
        ChannelIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChannelIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Channel> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Channel>("channel");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Channel>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Channel>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Channel`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait channelQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Channel`.
    fn channel(&self) -> __sdk::__query_builder::Table<Channel>;
}

impl channelQueryTableAccess for __sdk::QueryTableAccessor {
    fn channel(&self) -> __sdk::__query_builder::Table<Channel> {
        __sdk::__query_builder::Table::new("channel")
    }
}
