// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::channel_type_type::ChannelType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Channel {
    pub id: u64,
    pub server_id: u64,
    pub name: String,
    pub topic: Option<String>,
    pub channel_type: ChannelType,
    pub position: u32,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Channel {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Channel`.
///
/// Provides typed access to columns for query building.
pub struct ChannelCols {
    pub id: __sdk::__query_builder::Col<Channel, u64>,
    pub server_id: __sdk::__query_builder::Col<Channel, u64>,
    pub name: __sdk::__query_builder::Col<Channel, String>,
    pub topic: __sdk::__query_builder::Col<Channel, Option<String>>,
    pub channel_type: __sdk::__query_builder::Col<Channel, ChannelType>,
    pub position: __sdk::__query_builder::Col<Channel, u32>,
    pub created_at: __sdk::__query_builder::Col<Channel, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Channel {
    type Cols = ChannelCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChannelCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            server_id: __sdk::__query_builder::Col::new(table_name, "server_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            topic: __sdk::__query_builder::Col::new(table_name, "topic"),
            channel_type: __sdk::__query_builder::Col::new(table_name, "channel_type"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Channel`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChannelIxCols {
    pub id: __sdk::__query_builder::IxCol<Channel, u64>,
    pub server_id: __sdk::__query_builder::IxCol<Channel, u64>,
}

impl __sdk::__query_builder::HasIxCols for Channel {
    type IxCols = ChannelIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChannelIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            server_id: __sdk::__query_builder::IxCol::new(table_name, "server_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Channel {}
