// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DirectMessage {
    pub id: u64,
    pub conversation_id: u64,
    pub sender: __sdk::Identity,
    pub content: String,
    pub created_at: __sdk::Timestamp,
    pub edited_at: Option<__sdk::Timestamp>,
    pub read: bool,
}

impl __sdk::InModule for DirectMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DirectMessage`.
///
/// Provides typed access to columns for query building.
pub struct DirectMessageCols {
    pub id: __sdk::__query_builder::Col<DirectMessage, u64>,
    pub conversation_id: __sdk::__query_builder::Col<DirectMessage, u64>,
    pub sender: __sdk::__query_builder::Col<DirectMessage, __sdk::Identity>,
    pub content: __sdk::__query_builder::Col<DirectMessage, String>,
    pub created_at: __sdk::__query_builder::Col<DirectMessage, __sdk::Timestamp>,
    pub edited_at: __sdk::__query_builder::Col<DirectMessage, Option<__sdk::Timestamp>>,
    pub read: __sdk::__query_builder::Col<DirectMessage, bool>,
}

impl __sdk::__query_builder::HasCols for DirectMessage {
    type Cols = DirectMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DirectMessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            conversation_id: __sdk::__query_builder::Col::new(table_name, "conversation_id"),
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            edited_at: __sdk::__query_builder::Col::new(table_name, "edited_at"),
            read: __sdk::__query_builder::Col::new(table_name, "read"),
        }
    }
}

/// Indexed column accessor struct for the table `DirectMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct DirectMessageIxCols {
    pub conversation_id: __sdk::__query_builder::IxCol<DirectMessage, u64>,
    pub id: __sdk::__query_builder::IxCol<DirectMessage, u64>,
}

impl __sdk::__query_builder::HasIxCols for DirectMessage {
    type IxCols = DirectMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DirectMessageIxCols {
            conversation_id: __sdk::__query_builder::IxCol::new(table_name, "conversation_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DirectMessage {}
