// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::direct_conversation_type::DirectConversation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `direct_conversation`.
///
/// Obtain a handle from the [`DirectConversationTableAccess::direct_conversation`] method on [`super::RemoteTables`],
/// like `ctx.db.direct_conversation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_conversation().on_insert(...)`.
pub struct DirectConversationTableHandle<'ctx> {
    imp: __sdk::TableHandle<DirectConversation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `direct_conversation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DirectConversationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DirectConversationTableHandle`], which mediates access to the table `direct_conversation`.
    fn direct_conversation(&self) -> DirectConversationTableHandle<'_>;
}

impl DirectConversationTableAccess for super::RemoteTables {
    fn direct_conversation(&self) -> DirectConversationTableHandle<'_> {
        DirectConversationTableHandle {
            imp: self
                .imp
                .get_table::<DirectConversation>("direct_conversation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DirectConversationInsertCallbackId(__sdk::CallbackId);
pub struct DirectConversationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DirectConversationTableHandle<'ctx> {
    type Row = DirectConversation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DirectConversation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DirectConversationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DirectConversationInsertCallbackId {
        DirectConversationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DirectConversationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DirectConversationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DirectConversationDeleteCallbackId {
        DirectConversationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DirectConversationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DirectConversationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DirectConversationTableHandle<'ctx> {
    type UpdateCallbackId = DirectConversationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DirectConversationUpdateCallbackId {
        DirectConversationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DirectConversationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `direct_conversation`,
/// which allows point queries on the field of the same name
/// via the [`DirectConversationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_conversation().id().find(...)`.
pub struct DirectConversationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DirectConversation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DirectConversationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `direct_conversation`.
    pub fn id(&self) -> DirectConversationIdUnique<'ctx> {
        DirectConversationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DirectConversationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DirectConversation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DirectConversation>("direct_conversation");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DirectConversation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DirectConversation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DirectConversation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait direct_conversationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DirectConversation`.
    fn direct_conversation(&self) -> __sdk::__query_builder::Table<DirectConversation>;
}

impl direct_conversationQueryTableAccess for __sdk::QueryTableAccessor {
    fn direct_conversation(&self) -> __sdk::__query_builder::Table<DirectConversation> {
        __sdk::__query_builder::Table::new("direct_conversation")
    }
}
