// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DirectConversation {
    pub id: u64,
    pub participant_a: __sdk::Identity,
    pub participant_b: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
    pub last_message_at: __sdk::Timestamp,
}

impl __sdk::InModule for DirectConversation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DirectConversation`.
///
/// Provides typed access to columns for query building.
pub struct DirectConversationCols {
    pub id: __sdk::__query_builder::Col<DirectConversation, u64>,
    pub participant_a: __sdk::__query_builder::Col<DirectConversation, __sdk::Identity>,
    pub participant_b: __sdk::__query_builder::Col<DirectConversation, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<DirectConversation, __sdk::Timestamp>,
    pub last_message_at: __sdk::__query_builder::Col<DirectConversation, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for DirectConversation {
    type Cols = DirectConversationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DirectConversationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            participant_a: __sdk::__query_builder::Col::new(table_name, "participant_a"),
            participant_b: __sdk::__query_builder::Col::new(table_name, "participant_b"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_message_at: __sdk::__query_builder::Col::new(table_name, "last_message_at"),
        }
    }
}

/// Indexed column accessor struct for the table `DirectConversation`.
///
/// Provides typed access to indexed columns for query building.
pub struct DirectConversationIxCols {
    pub id: __sdk::__query_builder::IxCol<DirectConversation, u64>,
}

impl __sdk::__query_builder::HasIxCols for DirectConversation {
    type IxCols = DirectConversationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DirectConversationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DirectConversation {}
