// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::direct_message_type::DirectMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `direct_message`.
///
/// Obtain a handle from the [`DirectMessageTableAccess::direct_message`] method on [`super::RemoteTables`],
/// like `ctx.db.direct_message()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_message().on_insert(...)`.
pub struct DirectMessageTableHandle<'ctx> {
    imp: __sdk::TableHandle<DirectMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `direct_message`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DirectMessageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DirectMessageTableHandle`], which mediates access to the table `direct_message`.
    fn direct_message(&self) -> DirectMessageTableHandle<'_>;
}

impl DirectMessageTableAccess for super::RemoteTables {
    fn direct_message(&self) -> DirectMessageTableHandle<'_> {
        DirectMessageTableHandle {
            imp: self.imp.get_table::<DirectMessage>("direct_message"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DirectMessageInsertCallbackId(__sdk::CallbackId);
pub struct DirectMessageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DirectMessageTableHandle<'ctx> {
    type Row = DirectMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DirectMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DirectMessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DirectMessageInsertCallbackId {
        DirectMessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DirectMessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DirectMessageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DirectMessageDeleteCallbackId {
        DirectMessageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DirectMessageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DirectMessageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DirectMessageTableHandle<'ctx> {
    type UpdateCallbackId = DirectMessageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DirectMessageUpdateCallbackId {
        DirectMessageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DirectMessageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `direct_message`,
/// which allows point queries on the field of the same name
/// via the [`DirectMessageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_message().id().find(...)`.
pub struct DirectMessageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DirectMessage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DirectMessageTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `direct_message`.
    pub fn id(&self) -> DirectMessageIdUnique<'ctx> {
        DirectMessageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DirectMessageIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DirectMessage> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DirectMessage>("direct_message");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DirectMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DirectMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DirectMessage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait direct_messageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DirectMessage`.
    fn direct_message(&self) -> __sdk::__query_builder::Table<DirectMessage>;
}

impl direct_messageQueryTableAccess for __sdk::QueryTableAccessor {
    fn direct_message(&self) -> __sdk::__query_builder::Table<DirectMessage> {
        __sdk::__query_builder::Table::new("direct_message")
    }
}
