// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkDmReadArgs {
    pub conversation_id: u64,
}

impl From<MarkDmReadArgs> for super::Reducer {
    fn from(args: MarkDmReadArgs) -> Self {
        Self::MarkDmRead {
            conversation_id: args.conversation_id,
        }
    }
}

impl __sdk::InModule for MarkDmReadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_dm_read`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_dm_read {
    /// Request that the remote module invoke the reducer `mark_dm_read` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`mark_dm_read:mark_dm_read_then`] to run a callback after the reducer completes.
    fn mark_dm_read(&self, conversation_id: u64) -> __sdk::Result<()> {
        self.mark_dm_read_then(conversation_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `mark_dm_read` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn mark_dm_read_then(
        &self,
        conversation_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl mark_dm_read for super::RemoteReducers {
    fn mark_dm_read_then(
        &self,
        conversation_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MarkDmReadArgs { conversation_id }, callback)
    }
}
