// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::message_type_type::MessageType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Message {
    pub id: u64,
    pub channel_id: u64,
    pub thread_id: Option<u64>,
    pub sender: __sdk::Identity,
    pub content: String,
    pub message_type: MessageType,
    pub created_at: __sdk::Timestamp,
    pub edited_at: Option<__sdk::Timestamp>,
    pub reply_to_id: Option<u64>,
}

impl __sdk::InModule for Message {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Message`.
///
/// Provides typed access to columns for query building.
pub struct MessageCols {
    pub id: __sdk::__query_builder::Col<Message, u64>,
    pub channel_id: __sdk::__query_builder::Col<Message, u64>,
    pub thread_id: __sdk::__query_builder::Col<Message, Option<u64>>,
    pub sender: __sdk::__query_builder::Col<Message, __sdk::Identity>,
    pub content: __sdk::__query_builder::Col<Message, String>,
    pub message_type: __sdk::__query_builder::Col<Message, MessageType>,
    pub created_at: __sdk::__query_builder::Col<Message, __sdk::Timestamp>,
    pub edited_at: __sdk::__query_builder::Col<Message, Option<__sdk::Timestamp>>,
    pub reply_to_id: __sdk::__query_builder::Col<Message, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for Message {
    type Cols = MessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            channel_id: __sdk::__query_builder::Col::new(table_name, "channel_id"),
            thread_id: __sdk::__query_builder::Col::new(table_name, "thread_id"),
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            message_type: __sdk::__query_builder::Col::new(table_name, "message_type"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            edited_at: __sdk::__query_builder::Col::new(table_name, "edited_at"),
            reply_to_id: __sdk::__query_builder::Col::new(table_name, "reply_to_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Message`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageIxCols {
    pub channel_id: __sdk::__query_builder::IxCol<Message, u64>,
    pub id: __sdk::__query_builder::IxCol<Message, u64>,
}

impl __sdk::__query_builder::HasIxCols for Message {
    type IxCols = MessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageIxCols {
            channel_id: __sdk::__query_builder::IxCol::new(table_name, "channel_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Message {}
