// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_reaction_reducer;
pub mod archive_thread_reducer;
pub mod channel_read_state_table;
pub mod channel_read_state_type;
pub mod channel_table;
pub mod channel_type;
pub mod channel_type_type;
pub mod create_channel_reducer;
pub mod create_server_reducer;
pub mod create_thread_reducer;
pub mod delete_channel_reducer;
pub mod delete_direct_message_reducer;
pub mod delete_message_reducer;
pub mod delete_server_reducer;
pub mod direct_conversation_table;
pub mod direct_conversation_type;
pub mod direct_message_table;
pub mod direct_message_type;
pub mod edit_direct_message_reducer;
pub mod edit_message_reducer;
pub mod join_server_reducer;
pub mod leave_server_reducer;
pub mod mark_dm_read_reducer;
pub mod mark_read_reducer;
pub mod member_role_type;
pub mod message_table;
pub mod message_type;
pub mod message_type_type;
pub mod reaction_table;
pub mod reaction_type;
pub mod register_agent_reducer;
pub mod remove_reaction_reducer;
pub mod send_direct_message_reducer;
pub mod send_message_reducer;
pub mod server_member_table;
pub mod server_member_type;
pub mod server_table;
pub mod server_type;
pub mod set_profile_reducer;
pub mod start_typing_reducer;
pub mod system_notification_table;
pub mod system_notification_type;
pub mod thread_table;
pub mod thread_type;
pub mod typing_indicator_table;
pub mod typing_indicator_type;
pub mod update_channel_reducer;
pub mod update_member_role_reducer;
pub mod update_server_reducer;
pub mod user_presence_table;
pub mod user_presence_type;
pub mod user_profile_table;
pub mod user_profile_type;

pub use add_reaction_reducer::add_reaction;
pub use archive_thread_reducer::archive_thread;
pub use channel_read_state_table::*;
pub use channel_read_state_type::ChannelReadState;
pub use channel_table::*;
pub use channel_type::Channel;
pub use channel_type_type::ChannelType;
pub use create_channel_reducer::create_channel;
pub use create_server_reducer::create_server;
pub use create_thread_reducer::create_thread;
pub use delete_channel_reducer::delete_channel;
pub use delete_direct_message_reducer::delete_direct_message;
pub use delete_message_reducer::delete_message;
pub use delete_server_reducer::delete_server;
pub use direct_conversation_table::*;
pub use direct_conversation_type::DirectConversation;
pub use direct_message_table::*;
pub use direct_message_type::DirectMessage;
pub use edit_direct_message_reducer::edit_direct_message;
pub use edit_message_reducer::edit_message;
pub use join_server_reducer::join_server;
pub use leave_server_reducer::leave_server;
pub use mark_dm_read_reducer::mark_dm_read;
pub use mark_read_reducer::mark_read;
pub use member_role_type::MemberRole;
pub use message_table::*;
pub use message_type::Message;
pub use message_type_type::MessageType;
pub use reaction_table::*;
pub use reaction_type::Reaction;
pub use register_agent_reducer::register_agent;
pub use remove_reaction_reducer::remove_reaction;
pub use send_direct_message_reducer::send_direct_message;
pub use send_message_reducer::send_message;
pub use server_member_table::*;
pub use server_member_type::ServerMember;
pub use server_table::*;
pub use server_type::Server;
pub use set_profile_reducer::set_profile;
pub use start_typing_reducer::start_typing;
pub use system_notification_table::*;
pub use system_notification_type::SystemNotification;
pub use thread_table::*;
pub use thread_type::Thread;
pub use typing_indicator_table::*;
pub use typing_indicator_type::TypingIndicator;
pub use update_channel_reducer::update_channel;
pub use update_member_role_reducer::update_member_role;
pub use update_server_reducer::update_server;
pub use user_presence_table::*;
pub use user_presence_type::UserPresence;
pub use user_profile_table::*;
pub use user_profile_type::UserProfile;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddReaction {
        message_id: u64,
        emoji: String,
    },
    ArchiveThread {
        thread_id: u64,
    },
    CreateChannel {
        server_id: u64,
        name: String,
        channel_type: ChannelType,
    },
    CreateServer {
        name: String,
        description: Option<String>,
    },
    CreateThread {
        channel_id: u64,
        name: String,
        initial_message: String,
    },
    DeleteChannel {
        channel_id: u64,
    },
    DeleteDirectMessage {
        message_id: u64,
    },
    DeleteMessage {
        message_id: u64,
    },
    DeleteServer {
        server_id: u64,
    },
    EditDirectMessage {
        message_id: u64,
        new_content: String,
    },
    EditMessage {
        message_id: u64,
        new_content: String,
    },
    JoinServer {
        server_id: u64,
    },
    LeaveServer {
        server_id: u64,
    },
    MarkDmRead {
        conversation_id: u64,
    },
    MarkRead {
        channel_id: u64,
        message_id: u64,
    },
    RegisterAgent {
        agent_name: String,
        description: String,
    },
    RemoveReaction {
        message_id: u64,
        emoji: String,
    },
    SendDirectMessage {
        recipient: __sdk::Identity,
        content: String,
    },
    SendMessage {
        channel_id: u64,
        content: String,
        thread_id: Option<u64>,
        reply_to_id: Option<u64>,
    },
    SetProfile {
        username: String,
        display_name: Option<String>,
        avatar_url: Option<String>,
        bio: Option<String>,
    },
    StartTyping {
        channel_id: u64,
    },
    UpdateChannel {
        channel_id: u64,
        name: Option<String>,
        topic: Option<String>,
    },
    UpdateMemberRole {
        server_id: u64,
        target_identity: __sdk::Identity,
        new_role: MemberRole,
    },
    UpdateServer {
        server_id: u64,
        name: Option<String>,
        description: Option<String>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddReaction { .. } => "add_reaction",
            Reducer::ArchiveThread { .. } => "archive_thread",
            Reducer::CreateChannel { .. } => "create_channel",
            Reducer::CreateServer { .. } => "create_server",
            Reducer::CreateThread { .. } => "create_thread",
            Reducer::DeleteChannel { .. } => "delete_channel",
            Reducer::DeleteDirectMessage { .. } => "delete_direct_message",
            Reducer::DeleteMessage { .. } => "delete_message",
            Reducer::DeleteServer { .. } => "delete_server",
            Reducer::EditDirectMessage { .. } => "edit_direct_message",
            Reducer::EditMessage { .. } => "edit_message",
            Reducer::JoinServer { .. } => "join_server",
            Reducer::LeaveServer { .. } => "leave_server",
            Reducer::MarkDmRead { .. } => "mark_dm_read",
            Reducer::MarkRead { .. } => "mark_read",
            Reducer::RegisterAgent { .. } => "register_agent",
            Reducer::RemoveReaction { .. } => "remove_reaction",
            Reducer::SendDirectMessage { .. } => "send_direct_message",
            Reducer::SendMessage { .. } => "send_message",
            Reducer::SetProfile { .. } => "set_profile",
            Reducer::StartTyping { .. } => "start_typing",
            Reducer::UpdateChannel { .. } => "update_channel",
            Reducer::UpdateMemberRole { .. } => "update_member_role",
            Reducer::UpdateServer { .. } => "update_server",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AddReaction { message_id, emoji } => {
                __sats::bsatn::to_vec(&add_reaction_reducer::AddReactionArgs {
                    message_id: message_id.clone(),
                    emoji: emoji.clone(),
                })
            }
            Reducer::ArchiveThread { thread_id } => {
                __sats::bsatn::to_vec(&archive_thread_reducer::ArchiveThreadArgs {
                    thread_id: thread_id.clone(),
                })
            }
            Reducer::CreateChannel {
                server_id,
                name,
                channel_type,
            } => __sats::bsatn::to_vec(&create_channel_reducer::CreateChannelArgs {
                server_id: server_id.clone(),
                name: name.clone(),
                channel_type: channel_type.clone(),
            }),
            Reducer::CreateServer { name, description } => {
                __sats::bsatn::to_vec(&create_server_reducer::CreateServerArgs {
                    name: name.clone(),
                    description: description.clone(),
                })
            }
            Reducer::CreateThread {
                channel_id,
                name,
                initial_message,
            } => __sats::bsatn::to_vec(&create_thread_reducer::CreateThreadArgs {
                channel_id: channel_id.clone(),
                name: name.clone(),
                initial_message: initial_message.clone(),
            }),
            Reducer::DeleteChannel { channel_id } => {
                __sats::bsatn::to_vec(&delete_channel_reducer::DeleteChannelArgs {
                    channel_id: channel_id.clone(),
                })
            }
            Reducer::DeleteDirectMessage { message_id } => {
                __sats::bsatn::to_vec(&delete_direct_message_reducer::DeleteDirectMessageArgs {
                    message_id: message_id.clone(),
                })
            }
            Reducer::DeleteMessage { message_id } => {
                __sats::bsatn::to_vec(&delete_message_reducer::DeleteMessageArgs {
                    message_id: message_id.clone(),
                })
            }
            Reducer::DeleteServer { server_id } => {
                __sats::bsatn::to_vec(&delete_server_reducer::DeleteServerArgs {
                    server_id: server_id.clone(),
                })
            }
            Reducer::EditDirectMessage {
                message_id,
                new_content,
            } => __sats::bsatn::to_vec(&edit_direct_message_reducer::EditDirectMessageArgs {
                message_id: message_id.clone(),
                new_content: new_content.clone(),
            }),
            Reducer::EditMessage {
                message_id,
                new_content,
            } => __sats::bsatn::to_vec(&edit_message_reducer::EditMessageArgs {
                message_id: message_id.clone(),
                new_content: new_content.clone(),
            }),
            Reducer::JoinServer { server_id } => {
                __sats::bsatn::to_vec(&join_server_reducer::JoinServerArgs {
                    server_id: server_id.clone(),
                })
            }
            Reducer::LeaveServer { server_id } => {
                __sats::bsatn::to_vec(&leave_server_reducer::LeaveServerArgs {
                    server_id: server_id.clone(),
                })
            }
            Reducer::MarkDmRead { conversation_id } => {
                __sats::bsatn::to_vec(&mark_dm_read_reducer::MarkDmReadArgs {
                    conversation_id: conversation_id.clone(),
                })
            }
            Reducer::MarkRead {
                channel_id,
                message_id,
            } => __sats::bsatn::to_vec(&mark_read_reducer::MarkReadArgs {
                channel_id: channel_id.clone(),
                message_id: message_id.clone(),
            }),
            Reducer::RegisterAgent {
                agent_name,
                description,
            } => __sats::bsatn::to_vec(&register_agent_reducer::RegisterAgentArgs {
                agent_name: agent_name.clone(),
                description: description.clone(),
            }),
            Reducer::RemoveReaction { message_id, emoji } => {
                __sats::bsatn::to_vec(&remove_reaction_reducer::RemoveReactionArgs {
                    message_id: message_id.clone(),
                    emoji: emoji.clone(),
                })
            }
            Reducer::SendDirectMessage { recipient, content } => {
                __sats::bsatn::to_vec(&send_direct_message_reducer::SendDirectMessageArgs {
                    recipient: recipient.clone(),
                    content: content.clone(),
                })
            }
            Reducer::SendMessage {
                channel_id,
                content,
                thread_id,
                reply_to_id,
            } => __sats::bsatn::to_vec(&send_message_reducer::SendMessageArgs {
                channel_id: channel_id.clone(),
                content: content.clone(),
                thread_id: thread_id.clone(),
                reply_to_id: reply_to_id.clone(),
            }),
            Reducer::SetProfile {
                username,
                display_name,
                avatar_url,
                bio,
            } => __sats::bsatn::to_vec(&set_profile_reducer::SetProfileArgs {
                username: username.clone(),
                display_name: display_name.clone(),
                avatar_url: avatar_url.clone(),
                bio: bio.clone(),
            }),
            Reducer::StartTyping { channel_id } => {
                __sats::bsatn::to_vec(&start_typing_reducer::StartTypingArgs {
                    channel_id: channel_id.clone(),
                })
            }
            Reducer::UpdateChannel {
                channel_id,
                name,
                topic,
            } => __sats::bsatn::to_vec(&update_channel_reducer::UpdateChannelArgs {
                channel_id: channel_id.clone(),
                name: name.clone(),
                topic: topic.clone(),
            }),
            Reducer::UpdateMemberRole {
                server_id,
                target_identity,
                new_role,
            } => __sats::bsatn::to_vec(&update_member_role_reducer::UpdateMemberRoleArgs {
                server_id: server_id.clone(),
                target_identity: target_identity.clone(),
                new_role: new_role.clone(),
            }),
            Reducer::UpdateServer {
                server_id,
                name,
                description,
            } => __sats::bsatn::to_vec(&update_server_reducer::UpdateServerArgs {
                server_id: server_id.clone(),
                name: name.clone(),
                description: description.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    channel: __sdk::TableUpdate<Channel>,
    channel_read_state: __sdk::TableUpdate<ChannelReadState>,
    direct_conversation: __sdk::TableUpdate<DirectConversation>,
    direct_message: __sdk::TableUpdate<DirectMessage>,
    message: __sdk::TableUpdate<Message>,
    reaction: __sdk::TableUpdate<Reaction>,
    server: __sdk::TableUpdate<Server>,
    server_member: __sdk::TableUpdate<ServerMember>,
    system_notification: __sdk::TableUpdate<SystemNotification>,
    thread: __sdk::TableUpdate<Thread>,
    typing_indicator: __sdk::TableUpdate<TypingIndicator>,
    user_presence: __sdk::TableUpdate<UserPresence>,
    user_profile: __sdk::TableUpdate<UserProfile>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "channel" => db_update
                    .channel
                    .append(channel_table::parse_table_update(table_update)?),
                "channel_read_state" => db_update
                    .channel_read_state
                    .append(channel_read_state_table::parse_table_update(table_update)?),
                "direct_conversation" => db_update
                    .direct_conversation
                    .append(direct_conversation_table::parse_table_update(table_update)?),
                "direct_message" => db_update
                    .direct_message
                    .append(direct_message_table::parse_table_update(table_update)?),
                "message" => db_update
                    .message
                    .append(message_table::parse_table_update(table_update)?),
                "reaction" => db_update
                    .reaction
                    .append(reaction_table::parse_table_update(table_update)?),
                "server" => db_update
                    .server
                    .append(server_table::parse_table_update(table_update)?),
                "server_member" => db_update
                    .server_member
                    .append(server_member_table::parse_table_update(table_update)?),
                "system_notification" => db_update
                    .system_notification
                    .append(system_notification_table::parse_table_update(table_update)?),
                "thread" => db_update
                    .thread
                    .append(thread_table::parse_table_update(table_update)?),
                "typing_indicator" => db_update
                    .typing_indicator
                    .append(typing_indicator_table::parse_table_update(table_update)?),
                "user_presence" => db_update
                    .user_presence
                    .append(user_presence_table::parse_table_update(table_update)?),
                "user_profile" => db_update
                    .user_profile
                    .append(user_profile_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.channel = cache
            .apply_diff_to_table::<Channel>("channel", &self.channel)
            .with_updates_by_pk(|row| &row.id);
        diff.channel_read_state = cache
            .apply_diff_to_table::<ChannelReadState>("channel_read_state", &self.channel_read_state)
            .with_updates_by_pk(|row| &row.id);
        diff.direct_conversation = cache
            .apply_diff_to_table::<DirectConversation>(
                "direct_conversation",
                &self.direct_conversation,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.direct_message = cache
            .apply_diff_to_table::<DirectMessage>("direct_message", &self.direct_message)
            .with_updates_by_pk(|row| &row.id);
        diff.message = cache
            .apply_diff_to_table::<Message>("message", &self.message)
            .with_updates_by_pk(|row| &row.id);
        diff.reaction = cache
            .apply_diff_to_table::<Reaction>("reaction", &self.reaction)
            .with_updates_by_pk(|row| &row.id);
        diff.server = cache
            .apply_diff_to_table::<Server>("server", &self.server)
            .with_updates_by_pk(|row| &row.id);
        diff.server_member = cache
            .apply_diff_to_table::<ServerMember>("server_member", &self.server_member)
            .with_updates_by_pk(|row| &row.id);
        diff.system_notification = cache
            .apply_diff_to_table::<SystemNotification>(
                "system_notification",
                &self.system_notification,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.thread = cache
            .apply_diff_to_table::<Thread>("thread", &self.thread)
            .with_updates_by_pk(|row| &row.id);
        diff.typing_indicator = cache
            .apply_diff_to_table::<TypingIndicator>("typing_indicator", &self.typing_indicator)
            .with_updates_by_pk(|row| &row.id);
        diff.user_presence = cache
            .apply_diff_to_table::<UserPresence>("user_presence", &self.user_presence)
            .with_updates_by_pk(|row| &row.identity);
        diff.user_profile = cache
            .apply_diff_to_table::<UserProfile>("user_profile", &self.user_profile)
            .with_updates_by_pk(|row| &row.identity);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "channel" => db_update
                    .channel
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "channel_read_state" => db_update
                    .channel_read_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "direct_conversation" => db_update
                    .direct_conversation
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "direct_message" => db_update
                    .direct_message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "reaction" => db_update
                    .reaction
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "server" => db_update
                    .server
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "server_member" => db_update
                    .server_member
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "system_notification" => db_update
                    .system_notification
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "thread" => db_update
                    .thread
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "typing_indicator" => db_update
                    .typing_indicator
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_presence" => db_update
                    .user_presence
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_profile" => db_update
                    .user_profile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "channel" => db_update
                    .channel
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "channel_read_state" => db_update
                    .channel_read_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "direct_conversation" => db_update
                    .direct_conversation
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "direct_message" => db_update
                    .direct_message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "reaction" => db_update
                    .reaction
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "server" => db_update
                    .server
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "server_member" => db_update
                    .server_member
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "system_notification" => db_update
                    .system_notification
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "thread" => db_update
                    .thread
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "typing_indicator" => db_update
                    .typing_indicator
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_presence" => db_update
                    .user_presence
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_profile" => db_update
                    .user_profile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    channel: __sdk::TableAppliedDiff<'r, Channel>,
    channel_read_state: __sdk::TableAppliedDiff<'r, ChannelReadState>,
    direct_conversation: __sdk::TableAppliedDiff<'r, DirectConversation>,
    direct_message: __sdk::TableAppliedDiff<'r, DirectMessage>,
    message: __sdk::TableAppliedDiff<'r, Message>,
    reaction: __sdk::TableAppliedDiff<'r, Reaction>,
    server: __sdk::TableAppliedDiff<'r, Server>,
    server_member: __sdk::TableAppliedDiff<'r, ServerMember>,
    system_notification: __sdk::TableAppliedDiff<'r, SystemNotification>,
    thread: __sdk::TableAppliedDiff<'r, Thread>,
    typing_indicator: __sdk::TableAppliedDiff<'r, TypingIndicator>,
    user_presence: __sdk::TableAppliedDiff<'r, UserPresence>,
    user_profile: __sdk::TableAppliedDiff<'r, UserProfile>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Channel>("channel", &self.channel, event);
        callbacks.invoke_table_row_callbacks::<ChannelReadState>(
            "channel_read_state",
            &self.channel_read_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DirectConversation>(
            "direct_conversation",
            &self.direct_conversation,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DirectMessage>(
            "direct_message",
            &self.direct_message,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Message>("message", &self.message, event);
        callbacks.invoke_table_row_callbacks::<Reaction>("reaction", &self.reaction, event);
        callbacks.invoke_table_row_callbacks::<Server>("server", &self.server, event);
        callbacks.invoke_table_row_callbacks::<ServerMember>(
            "server_member",
            &self.server_member,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SystemNotification>(
            "system_notification",
            &self.system_notification,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Thread>("thread", &self.thread, event);
        callbacks.invoke_table_row_callbacks::<TypingIndicator>(
            "typing_indicator",
            &self.typing_indicator,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UserPresence>(
            "user_presence",
            &self.user_presence,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UserProfile>(
            "user_profile",
            &self.user_profile,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        channel_table::register_table(client_cache);
        channel_read_state_table::register_table(client_cache);
        direct_conversation_table::register_table(client_cache);
        direct_message_table::register_table(client_cache);
        message_table::register_table(client_cache);
        reaction_table::register_table(client_cache);
        server_table::register_table(client_cache);
        server_member_table::register_table(client_cache);
        system_notification_table::register_table(client_cache);
        thread_table::register_table(client_cache);
        typing_indicator_table::register_table(client_cache);
        user_presence_table::register_table(client_cache);
        user_profile_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "channel",
        "channel_read_state",
        "direct_conversation",
        "direct_message",
        "message",
        "reaction",
        "server",
        "server_member",
        "system_notification",
        "thread",
        "typing_indicator",
        "user_presence",
        "user_profile",
    ];
}
