// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendDirectMessageArgs {
    pub recipient: __sdk::Identity,
    pub content: String,
}

impl From<SendDirectMessageArgs> for super::Reducer {
    fn from(args: SendDirectMessageArgs) -> Self {
        Self::SendDirectMessage {
            recipient: args.recipient,
            content: args.content,
        }
    }
}

impl __sdk::InModule for SendDirectMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_direct_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_direct_message {
    /// Request that the remote module invoke the reducer `send_direct_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`send_direct_message:send_direct_message_then`] to run a callback after the reducer completes.
    fn send_direct_message(
        &self,
        recipient: __sdk::Identity,
        content: String,
    ) -> __sdk::Result<()> {
        self.send_direct_message_then(recipient, content, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `send_direct_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn send_direct_message_then(
        &self,
        recipient: __sdk::Identity,
        content: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl send_direct_message for super::RemoteReducers {
    fn send_direct_message_then(
        &self,
        recipient: __sdk::Identity,
        content: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SendDirectMessageArgs { recipient, content }, callback)
    }
}
