// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetProfileArgs {
    pub username: String,
    pub display_name: Option<String>,
    pub avatar_url: Option<String>,
    pub bio: Option<String>,
}

impl From<SetProfileArgs> for super::Reducer {
    fn from(args: SetProfileArgs) -> Self {
        Self::SetProfile {
            username: args.username,
            display_name: args.display_name,
            avatar_url: args.avatar_url,
            bio: args.bio,
        }
    }
}

impl __sdk::InModule for SetProfileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_profile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_profile {
    /// Request that the remote module invoke the reducer `set_profile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_profile:set_profile_then`] to run a callback after the reducer completes.
    fn set_profile(
        &self,
        username: String,
        display_name: Option<String>,
        avatar_url: Option<String>,
        bio: Option<String>,
    ) -> __sdk::Result<()> {
        self.set_profile_then(username, display_name, avatar_url, bio, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_profile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_profile_then(
        &self,
        username: String,
        display_name: Option<String>,
        avatar_url: Option<String>,
        bio: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_profile for super::RemoteReducers {
    fn set_profile_then(
        &self,
        username: String,
        display_name: Option<String>,
        avatar_url: Option<String>,
        bio: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetProfileArgs {
                username,
                display_name,
                avatar_url,
                bio,
            },
            callback,
        )
    }
}
