// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TypingIndicator {
    pub id: u64,
    pub channel_id: u64,
    pub identity: __sdk::Identity,
}

impl __sdk::InModule for TypingIndicator {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TypingIndicator`.
///
/// Provides typed access to columns for query building.
pub struct TypingIndicatorCols {
    pub id: __sdk::__query_builder::Col<TypingIndicator, u64>,
    pub channel_id: __sdk::__query_builder::Col<TypingIndicator, u64>,
    pub identity: __sdk::__query_builder::Col<TypingIndicator, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for TypingIndicator {
    type Cols = TypingIndicatorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TypingIndicatorCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            channel_id: __sdk::__query_builder::Col::new(table_name, "channel_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
        }
    }
}

/// Indexed column accessor struct for the table `TypingIndicator`.
///
/// Provides typed access to indexed columns for query building.
pub struct TypingIndicatorIxCols {
    pub id: __sdk::__query_builder::IxCol<TypingIndicator, u64>,
}

impl __sdk::__query_builder::HasIxCols for TypingIndicator {
    type IxCols = TypingIndicatorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TypingIndicatorIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TypingIndicator {}
