// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateServerArgs {
    pub server_id: u64,
    pub name: Option<String>,
    pub description: Option<String>,
}

impl From<UpdateServerArgs> for super::Reducer {
    fn from(args: UpdateServerArgs) -> Self {
        Self::UpdateServer {
            server_id: args.server_id,
            name: args.name,
            description: args.description,
        }
    }
}

impl __sdk::InModule for UpdateServerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_server`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_server {
    /// Request that the remote module invoke the reducer `update_server` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_server:update_server_then`] to run a callback after the reducer completes.
    fn update_server(
        &self,
        server_id: u64,
        name: Option<String>,
        description: Option<String>,
    ) -> __sdk::Result<()> {
        self.update_server_then(server_id, name, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_server` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_server_then(
        &self,
        server_id: u64,
        name: Option<String>,
        description: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_server for super::RemoteReducers {
    fn update_server_then(
        &self,
        server_id: u64,
        name: Option<String>,
        description: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateServerArgs {
                server_id,
                name,
                description,
            },
            callback,
        )
    }
}
