// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateChannelArgs {
    pub channel_id: u64,
    pub name: Option<String>,
    pub topic: Option<String>,
}

impl From<UpdateChannelArgs> for super::Reducer {
    fn from(args: UpdateChannelArgs) -> Self {
        Self::UpdateChannel {
            channel_id: args.channel_id,
            name: args.name,
            topic: args.topic,
        }
    }
}

impl __sdk::InModule for UpdateChannelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_channel {
    /// Request that the remote module invoke the reducer `update_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_channel:update_channel_then`] to run a callback after the reducer completes.
    fn update_channel(
        &self,
        channel_id: u64,
        name: Option<String>,
        topic: Option<String>,
    ) -> __sdk::Result<()> {
        self.update_channel_then(channel_id, name, topic, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_channel` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_channel_then(
        &self,
        channel_id: u64,
        name: Option<String>,
        topic: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_channel for super::RemoteReducers {
    fn update_channel_then(
        &self,
        channel_id: u64,
        name: Option<String>,
        topic: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateChannelArgs {
                channel_id,
                name,
                topic,
            },
            callback,
        )
    }
}
