// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserProfile {
    pub identity: __sdk::Identity,
    pub username: String,
    pub display_name: Option<String>,
    pub avatar_url: Option<String>,
    pub bio: Option<String>,
    pub is_agent: bool,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for UserProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserProfile`.
///
/// Provides typed access to columns for query building.
pub struct UserProfileCols {
    pub identity: __sdk::__query_builder::Col<UserProfile, __sdk::Identity>,
    pub username: __sdk::__query_builder::Col<UserProfile, String>,
    pub display_name: __sdk::__query_builder::Col<UserProfile, Option<String>>,
    pub avatar_url: __sdk::__query_builder::Col<UserProfile, Option<String>>,
    pub bio: __sdk::__query_builder::Col<UserProfile, Option<String>>,
    pub is_agent: __sdk::__query_builder::Col<UserProfile, bool>,
    pub created_at: __sdk::__query_builder::Col<UserProfile, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for UserProfile {
    type Cols = UserProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserProfileCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            avatar_url: __sdk::__query_builder::Col::new(table_name, "avatar_url"),
            bio: __sdk::__query_builder::Col::new(table_name, "bio"),
            is_agent: __sdk::__query_builder::Col::new(table_name, "is_agent"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `UserProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserProfileIxCols {
    pub identity: __sdk::__query_builder::IxCol<UserProfile, __sdk::Identity>,
    pub username: __sdk::__query_builder::IxCol<UserProfile, String>,
}

impl __sdk::__query_builder::HasIxCols for UserProfile {
    type IxCols = UserProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserProfileIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            username: __sdk::__query_builder::IxCol::new(table_name, "username"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserProfile {}
